### ISSUE TITLE
DOI for XCFun code via Zenodo

### ISSUE THREAD

**Issue by bast** [dftlibs/xcfun#101]
I have been tasked to make the code citeable, before Sunday night.

I can take care of that and get a DOI through https://zenodo.org but wanted to check:
- Any objections?
- From which hash? The one used by OpenRSP?
- Which semantic version should the code have?

**Comment by robertodr** [comment]
* No objections.
* I'd say the hash corresponding to the alpha1, which is the only official release so far.
* v2.0.0alpha1, as the latest tag.

**Comment by ilfreddy** [comment]
No objection and no opinion about the technical aspects.

Luca

**Comment by bast** [comment]
I need to check whether LSDalton/OpenRSP/XCint uses alpha1. If not, I might create two DOIs. Since I need to get a DOI for the version used by LSDalton/OpenRSP/XCint.

**Comment by robertodr** [comment]
LSDalton does not use alpha1.

**Comment by bast** [comment]
> LSDalton does not use alpha1.

So then I will have the challenge to name the tag corresponding to the version used by LSDalton.

**Comment by aspgomes** [comment]
On Thu, Dec 12, 2019 at 9:36 AM Luca Frediani <notifications@github.com>
wrote:

> No objection and no opinion about the technical aspects.
>

same here
