### ISSUE TITLE
Drop Python 2.7 support

### ISSUE THREAD

**Issue by robertodr** [dftlibs/xcfun#103]
Python 2.7 has reached end-of-life. It is currently failing one of the jobs in CI. I think we should just drop it and forget it exists.

**Comment by bast** [comment]
I agree. I think we should remove it from the CI pipelines.

**Comment by chjacob-tubs** [comment]
We are still in the process of converting PyADF to Python3, but I agree that you should drop the CI pipelines. This will give us another reason to really push the transition now ...

**Comment by robertodr** [comment]
See #103
