### ISSUE TITLE
`-m64` not recognized on the raspberry pi 3

### ISSUE THREAD

**Issue by ilfreddy** [dftlibs/xcfun#107]
I acknowledge this is most likely not the most pressing issue, but it seems the `-m64` flag is not working on the raspberry pi 3. Once I remove it I manage to compile XCFun :-)

**Comment by robertodr** [comment]
Indeed it's in the i386 and AMD x86-64 class of options to GCC. I am unsure what exactly that flag is supposed to accomplish, so it's highly likely safe to remove.

**Comment by bast** [comment]
+1. If the CI pipeline does not complain, I would merge this. Later if somebody really needs this, we will find out by another issue.
