### ISSUE TITLE
XCFun as a Spack package

### ISSUE THREAD

**Issue by robertodr** [dftlibs/xcfun#120]
XCFun is now available as a Spack package: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/xcfun/package.py

This should be mentioned in the `README.md` and in the docs.

**Comment by bast** [comment]
I will add that in my round when working on #119.

**Comment by robertodr** [comment]
Thank you! XCFun can now be installed in a Spack environment with:
```
spack env create myenv
spack env activate myenv
spack install xcfun
```
The Python module will be available on `PYTHONPATH`.

**Comment by bast** [comment]
Thanks I will add that info and then you can refine it.
