### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by sunqm** [dftlibs/xcfun#13]
Hi,

The APIs of master branch are not compatible to old release 1.x.  It affects at least the following functions:
xc_output_length
xc_eval
xc_eval_vec

Qiming

**Comment by bast** [comment]
Dear Qiming, this is correct, the API has changed - I will soon document the updated API.

**Comment by bast** [comment]
The `stable-1.x` branch contains the code which was previously on `master` (I have renamed the branches yesterday to make more clear where the main line development is).

**Comment by bast** [comment]
Over the summer I will clean up the docs. Sorry again for the confusion.
