### ISSUE TITLE
SCAN functionals return NaN values for small density gradients

### ISSUE THREAD

**Issue by fishjojo** [dftlibs/xcfun#144]
The following code returns either `NaN` for functional derivatives or crashes with error ```void pow_expand(T*, T, T) [with T = double; int N = 2]: Assertion `x0 > 0 && "pow(x,a) not real analytic at x <= 0"' failed.```
```
int main()
{
  double* rho = malloc(sizeof(double) * 3);
  rho[0] = 1.56340410e-09;
  rho[1] = 5.24324068e-18;
  rho[2] = 4.19259161e-10;

  int fn_id = 46;
  xcfun_t* fun = xcfun_new();
  const char* name = xcfun_enumerate_parameters(fn_id);
  xcfun_set(fun, name, 1.0);

  xcfun_eval_setup(fun, XC_N_GNN_TAUN, XC_PARTIAL_DERIVATIVES, 1);
  int outlen = xcfun_output_length(fun);
  double* output = malloc(sizeof(double) * outlen);

  xcfun_eval(fun, rho, output);
  xcfun_delete(fun);

  for(int i=0; i<outlen; i++){
    printf("%f\n", output[i]);
  }
}
```
I think this is caused by the following lines of code
https://github.com/dftlibs/xcfun/blob/65c1ea46a2258d01ef8c680bc2d306a93ab56da7/src/functionals/SCAN_like_eps.hpp#L118-L124
where `s` is always 0 when `d_g` is smaller than 1e-16.

**Comment by bast** [comment]
Thanks for reporting this and for locating the problem!

**Comment by robertodr** [comment]
@JFurness1 @bast do you have an idea how to fix this directly in the XCFun source code?

**Comment by JFurness1** [comment]
I'll take a look at this now. I've probably made a poor choice for regularising the gradient somewhere along the way.

**Comment by robertodr** [comment]
That was amazingly quick James! Please open another pull request with the patch. Thanks again!

**Comment by JFurness1** [comment]
No problem, it was a pretty glaring error I should have seen before really! I'm surprised it got this far without showing up.

I've opened the pull request. Hopefully I go that all correct, I'm still finding my feet around git's wider fork/pull request features.

**Comment by robertodr** [comment]
@fishjojo would you be able to try if latest `master` fixes the problems you observed in PySCF? Thank you.

**Comment by fishjojo** [comment]
Yes, this fixes the problem. Thanks.

**Comment by JFurness1** [comment]
Great! I'm glad it was an easy fix!

**Comment by bast** [comment]
Thanks so much James and everybody! Sorry for answering late. Meetings all the time :-)

**Comment by robertodr** [comment]
Excellent! I'll prepare a new release in the morning, after updating the
changelog.
