### ISSUE TITLE
Implementing a new functional on a basis of Slater exchange

### ISSUE THREAD

**Issue by alexmir18** [dftlibs/xcfun#150]
Hello,
This is not really an issue, but a question. I would like to compute an integral over electron density to some power n for my research. A natural approach would be to start with the Slater exchange functional and modify its prefactor and exponent. I tried to locate a function that evaluates such integral in the xcfun library, but couldn't. If you could advise on how this can be done, I would highly appreciate it. Thanks!

Alex

**Comment by robertodr** [comment]
Hello! You might want to have a look at these two files https://github.com/dftlibs/xcfun/blob/master/src/functionals/slater.hpp and https://github.com/dftlibs/xcfun/blob/master/src/functionals/slaterx.cpp to get started.

**Comment by bast** [comment]
If you are interested in a relatively lightweight way to generate a numerical integration grid to integrate that density, check out https://github.com/dftlibs/numgrid (I am the developer of the latter, not saying this for self promotion but that I am happy to help with that one if you go for it).

**Comment by alexmir18** [comment]
Thanks! I will take a look at slater cpp/hpp files and check out the numerical integration grid. Thank you for the suggestion!
