### ISSUE TITLE
Compiler error brx.cpp

### ISSUE THREAD

**Issue by levineds** [dftlibs/xcfun#157]
With v2.1.1, I can compile without issue. With the current master, I crash with this error:
<username>/xcfun/src/functionals/brx.cpp: In function ‘taylor<T, 1, N> BR_taylor(const T&)’:
<username>/xcfun/src/functionals/brx.cpp:54:26: error: expected ‘,’ before ‘)’ token
   static_assert(Ndeg >= 3);
                          ^
<username>/xcfun/src/functionals/brx.cpp:54:26: error: expected string-literal before ‘)’ token

Using gcc/g++ 9.3.1 on Centos7

**Comment by robertodr** [comment]
My bad... `static_assert` needs a second arguments pre-C++17. Patch incoming
