### ISSUE TITLE
Re-licensing under the Mozilla Public License version 2

### ISSUE THREAD

**Issue by robertodr** [dftlibs/xcfun#17]
The project comes under the [LGPL3.0+](https://www.gnu.org/licenses/lgpl-3.0.en.html) with a [Static Linking Exception (SLE)](http://zeromq.org/area:licensing) It could be worthwhile to re-license under [MPLv2](https://www.mozilla.org/en-US/MPL/2.0/), since it has the SLE baked in and is a standard license.

This is the list of contributors according to `git shortlog --summary --numbered`

- [x] @ajborgoo 
- [x] @aspgomes 
- [x] @chjacob-tubs 
- [x] @erebolini 
- [x] @juselius
- [x] @miroi
- [x] @bast 
- [x] @robertodr
- [x] @sarahr
- [x] @simensr 
- [x] @uekstrom 

Could you: 
1. kindly reply "I hereby agree to publish my contributions to XCFun under the MPLv2 license"?
2. Open a pull request to add a file in the `RELICENSE` subdirectory of the repository following [this template](https://github.com/robertodr/xcfun/blob/relicense/RELICENSE/relicense-template-mplv2.txt)
This action is needed in order to leave a "paper trail" of the relicensing (much like the relicensing process in DALTON/LSDALTON)

If you have any objection to relicensing your contributions, explain your reasons

**Comment by bast** [comment]
I support it. MPLv2.0 is two-way remixable but probably simpler with regards to re-linking requirement. We will however need support from all [past contributors](https://github.com/dftlibs/xcfun/graphs/contributors).

**Comment by robertodr** [comment]
_Ça va sans dire_ :wink: I think we need two steps:
1. Open an issue asking for relicensing under MPLv2, [like here](https://github.com/zeromq/zyre/issues/327)
2. Create a paper trail in the repository [like here](https://github.com/zeromq/libzmq/tree/master/RELICENSE)

**Comment by uekstrom** [comment]
I'm fine with the mplv2.

Ulf

**Comment by aspgomes** [comment]
i'm fine with it too.

**Comment by robertodr** [comment]
I hereby agree to publish my contributions to XCFun under the MPLv2 license

**Comment by chjacob-tubs** [comment]
I hereby agree to publish my contributions to XCFun under the MPLv2 license

**Comment by ajborgoo** [comment]
I hereby agree to publish my contributions to XCFun under the MPLv2 license

**Comment by simensr** [comment]
I hereby agree to publish my contributions to XCFun under the MPLv2 license

**Comment by erebolini** [comment]
I hereby agree to publish my contributions to XCFun under the MPLv2 license

**Comment by sarahr** [comment]
I hereby agree to publish my contributions to XCFun under the MPLv2 license

**Comment by robertodr** [comment]
You should now file a pull request to add a [file like this](https://github.com/dftlibs/xcfun/tree/master/RELICENSE) to the repository. You can click on "Create new file", copy-paste the [template](https://github.com/dftlibs/xcfun/blob/master/RELICENSE/relicense-template-mplv2.txt) and then submit. Please close the commit message with [ci skip], so that unnecessary CI builds are avoided. Thank you in advance!

**Comment by miroi** [comment]
I hereby agree to publish my contributions to XCFun under the MPLv2 license

**Comment by simensr** [comment]
Reminder for @ajborgoo @erebolini @juselius  @sarahr @uekstrom

**Comment by uekstrom** [comment]
I hereby agree to publish my contributions to XCFun under the MPLv2 license

**Comment by robertodr** [comment]
This issue has been open for a while and I would like to close it. If you haven't done so yet, I reiterate my request to @ajborgoo @erebolini @juselius @sarahr @uekstrom to reply to this issue and to generate a new file in the `RELICENSE` folder following the [template](https://github.com/dftlibs/xcfun/blob/master/RELICENSE/relicense-template-mplv2.txt)
1. Go to https://github.com/dftlibs/xcfun
2. Click on the `RELICENSE` folder.
3. Click on `Create new file`
![untitled](https://user-images.githubusercontent.com/3708689/32841793-9a5e0dc6-ca1b-11e7-8dd1-70e26dd3c41a.png)
4. Copy-paste the template into the editor window and edit the placeholders (`{{ name of company / name of individual }}`, `{{github username}}`, `{{github commit author}}`, `{{name}}`, `{{ Full Name }}` and `{{ creation date of document (format: yyyy/mm/dd) }}`) with the correct content.
5. The new file should be saved as `NameSurname.md`.
![selection_001](https://user-images.githubusercontent.com/3708689/32842617-d2f9c1be-ca1d-11e7-839f-65c5316faa14.png)
6. The commit message should state that the new file was created and should have the `[ci skip]` tag, so that CI jobs on Travis are not triggered.
7. You can save the new file. This should automatically submit a pull request with your changes.

**Comment by uekstrom** [comment]
Thank you Robert for your excellent instructions! I have committed my file.

Regards,
Ulf

2017-11-15 16:01 GMT+01:00 Roberto Di Remigio <notifications@github.com>:

**Comment by juselius** [comment]
I hereby agree to publish my contributions to XCFun under the MPLv2 license

**Comment by robertodr** [comment]
**REMINDER**
This issue has been open for a while and I would like to close it. If you haven't done so yet, I reiterate my request to @ajborgoo @erebolini to reply to this issue and to generate a new file in the `RELICENSE` folder following the [template](https://github.com/dftlibs/xcfun/blob/master/RELICENSE/relicense-template-mplv2.txt)
1. Go to https://github.com/dftlibs/xcfun
2. Click on the `RELICENSE` folder.
3. Click on `Create new file`
![untitled](https://user-images.githubusercontent.com/3708689/32841793-9a5e0dc6-ca1b-11e7-8dd1-70e26dd3c41a.png)
4. Copy-paste the template into the editor window and edit the placeholders (`{{ name of company / name of individual }}`, `{{github username}}`, `{{github commit author}}`, `{{name}}`, `{{ Full Name }}` and `{{ creation date of document (format: yyyy/mm/dd) }}`) with the correct content.
5. The new file should be saved as `NameSurname.md`.
![selection_001](https://user-images.githubusercontent.com/3708689/32842617-d2f9c1be-ca1d-11e7-839f-65c5316faa14.png)
6. The commit message should state that the new file was created and should have the `[ci skip]` tag, so that CI jobs on Travis are not triggered.
7. You can save the new file. This should automatically submit a pull request with your changes.

**Comment by bast** [comment]
@robertodr everybody is checked on top but I guess @ajborgoo is missing?

**Comment by ajborgoo** [comment]
Now GitHub proposes to do a pull request. Should I do this, or has it been done automatically (as it said in the previous window?)
A

**Comment by robertodr** [comment]
Thanks @ajborgoo and yes, go ahead with the PR.
