### ISSUE TITLE
[Testing] ALL tests failing on Travis

### ISSUE THREAD

**Issue by robertodr** [dftlibs/xcfun#24]
The `kernel_example` test is failing on **ALL** testing architectures. This was noticed also by @miroi on MS Windows in #12.

**Comment by bast** [comment]
Yes - confirming that it is broken. It is on my TODO list since a long time to fix it and it is good that this got elevated and bumped in my memory stack.

**Comment by robertodr** [comment]
If you point me to a starting point, I can look around to see if I am able
to find a fix.

Il mer 14 giu 2017, 12:02 Radovan Bast <notifications@github.com> ha
scritto:
