### ISSUE TITLE
Outdated documentation 

### ISSUE THREAD

**Issue by fabijan5** [dftlibs/xcfun#32]
I have noticed that the definition on how to call certain functions from the "http://dftlibs.org/xcfun/" webpage is outdated. For example, when specifying the functions such as:
xc_set_mode(fun, XC_VARS_AB);

error is reported:
error: use of undeclared identifier
      'XC_VARS_AB'
    xc_set_mode(fun, XC_VARS_AB);

**Comment by bast** [comment]
Thanks for reporting and sorry for the confusion! It is indeed on my desk to clean it up. I will self-assign once I really start working on this, though.

**Comment by robertodr** [comment]
Working on this in #106 Documentation will appear on xcfun.readthedocs.io
