### ISSUE TITLE
Update CMake infrastructure and remove explicit Makefiles

### ISSUE THREAD

**Issue by bast** [dftlibs/xcfun#34]
I suggest to update CMake infrastructure to http://autocmake.readthedocs.io and to remove the explicit Makefiles to avoid code repetition and editing configuration in two places when refactoring code.

Before I embark on this, are there any opposing views on this?

**Comment by robertodr** [comment]
No objections from me!

**Comment by bast** [comment]
OK - self-assigning. Will open a PR soon and it can still be stopped then but IMO two build frameworks in parallel are not long-term maintainable.
