### ISSUE TITLE
add/clean  some documentation on installation,usage  

### ISSUE THREAD

**Issue by miroi** [dftlibs/xcfun#4]
Hi,

would  you please write INSTALL and clean/repair  the doc file, 
https://github.com/dftlibs/xcfun/blob/master/doc/xcfun_doc.html  ?

Would be glad to try some work with xcfun. Thanks.

**Comment by uekstrom** [comment]
Dear Miro,
this is unlikely to happen until the next xcfun version is ready.
Installation is not difficult, just compile using
the makefile for your platform and use the libxcfun.a. Use the ng branch if
possible.

Regards,
Ulf

2016-02-10 18:01 GMT+01:00 Miro Iliaš <notifications@github.com>:

**Comment by bast** [comment]
My plan is to soon update the docs.

**Comment by robertodr** [comment]
Working on this in #106
