### ISSUE TITLE
Python interface is untested during automated tests

### ISSUE THREAD

**Issue by bast** [dftlibs/xcfun#43]
It is too easy to break code when it is untested.

**Comment by chjacob-tubs** [comment]
Can you give a a hint where the automatic tests are and how I can run / test them? I will try to take care of this then.

**Comment by bast** [comment]
We use Travis and Appveyor:
- https://github.com/dftlibs/xcfun/blob/master/.travis.yml#L190
- https://github.com/dftlibs/xcfun/blob/master/.appveyor.yml

Step one would be to make them part of the "test" target:
- https://github.com/dftlibs/xcfun/blob/master/test/CMakeLists.txt

**Comment by chjacob-tubs** [comment]
Fixed with #93
