### ISSUE TITLE
Order of xc_vars in xcfun.h is not intuitive

### ISSUE THREAD

**Issue by bast** [dftlibs/xcfun#45]
For instance `XC_N_NX_NY_NZ` shows up under meta-GGA.

**Comment by ilfreddy** [comment]
I think this issue might be merged with the one I created. I assume the comments (LDA/GGA/metaGGA) interspaced in the list are old and should simply be removed.
It makes indeed more sense to order them in terms of the number of expected input functions.

**Comment by bast** [comment]
I will add some more doc there to clarify. PR incoming.
