### ISSUE TITLE
cmake for shared library

### ISSUE THREAD

**Issue by sunqm** [dftlibs/xcfun#5]
Hi,

Would you please remove the "ARCHIVE" from

install(TARGETS xcfun ARCHIVE DESTINATION lib)

in src/CMakeLists.txt

because this parameter prevents building the shared library with

cmake -DBUILD_SHARED_LIBS=1

Thank you!

**Comment by uekstrom** [comment]
I will, just checking with the cmake expert.

Regards,
Ulf

2016-02-15 20:57 GMT+01:00 Qiming Sun <notifications@github.com>:

**Comment by bast** [comment]
I will look into this and try to relax this constraint.
