### ISSUE TITLE
define XC_MAX_ORDER in cmake config

### ISSUE THREAD

**Issue by sunqm** [dftlibs/xcfun#6]
Hi,

It'd be better if XC_MAX_ORDER was predefined in CMakeLists.txt instead of hardcode in the head file.  Setting the highest order with command line like "cmake -DXC_MAX_ORDER=2" is very useful for me.

**Comment by bast** [comment]
I agree that this would be good. I can take care of that. Since we also support Makefiles my idea is to use a hardcoded limit only if it was not set from the outside (CMake or Makefile).
