### ISSUE TITLE
Fortran API

### ISSUE THREAD

**Issue by robertodr** [dftlibs/xcfun#61]
The Fortran API is split between the `xcfun.F90` and the `fortran.c` files. As far as I can understand, this i to ensure Fortran/C interoperability _without_ using `iso_c_binding` since that is formally available only in Fortran 2003.
As of 2018, it can be safely assumed that all compilers have `iso_c_binding` properly implemented. Thus the two files can be unified and simplified. Ideally, `xcfun.f90` will be just a shim over the C API specification in `xcfun.h`.
Ideas/TODO points:
- Remove the need to preprocess `xcfun.F90`, _i.e._ `xcfun.f90` should be enough.
- Use `iso_c_binding` to fix types between Fortran and C.

**Comment by bast** [comment]
Good idea. This should also simplify/solve #53.

**Comment by robertodr** [comment]
Working on this (slowly) in #98
