### ISSUE TITLE
Python bindings not compiling anymore

### ISSUE THREAD

**Issue by chjacob-tubs** [dftlibs/xcfun#63]
The latest CMAKE changes break my Python setup (as already written by @robertodr in #59). 

I am working on fixing the problems (should be done soon). Opening this issue in case there is anything to discuss.

**Comment by bast** [comment]
OK I am assigning to you just to mark that somebody is working on it.

**Comment by bast** [comment]
But feel free to un-assign to mark that you want to hand over.

**Comment by robertodr** [comment]
Yeah, I had imagined that would happen. As I said, I could not manage to get the SWIG bindings to work even with the old CMake set up, so I couldn't really test the new one (apart from seeing it could compile that stuff)

**Comment by chjacob-tubs** [comment]
@robertodr As far as I understand, you have hidden some of the API in xcfun.h. The following hidden functions are needed by the Python bindings (at least in the current version, I would have to look closer to check if some of them could be removed / replaced):
xc_is_gga, xc_is_metagga, xc_eval_vec, xc_input_length
Is it OK if I make these visible again or is there some deeper logic behind this change that I dont see?

**Comment by robertodr** [comment]
At this point there is no deeper logic yet, so go ahead and expose them by prepending the `XCFun_API` macro. I was not able to get the Python bindings to work even before the visibility change though. (Again, I apologize for breaking a lot of your stuff)
