### ISSUE TITLE
Announcements and planning

### ISSUE THREAD

**Issue by robertodr** [dftlibs/xcfun#66]
There will be some activity in the next months, to modernize the code base and fix some pending issues regarding the Fortran and Python bindings to the XCFun API. I think we need some planning to avoid disrupting the work of people relying on XCFun. I am putting up some points and I'd invite everyone who's interested to chip in in the discussion. We can then break off into smaller issues.

#### Official version 2.0
XCFun is at version 2.0, but sort of unofficially. #59 broke Python bindings using SWIG and @chjacob-tubs is working on restoring those. I propose:
- A `v2.0.0` tag is minted when #63 and #43 are fixed
- The project gets a [Zenodo DOI](https://zenodo.org/)

#### Conda packaging
It would be good to distribute a precompiled version through [Anaconda Cloud](https://anaconda.org/) The library is sufficiently self-contained that it shouldn't be too problematic.

**Comment by bast** [comment]
I agree with v2.0 and DOI. Very important. I think before we invest time in Conda we have to clean up the documentation and website. Simplifying installation is very important but currently it's not too easy to get started with using the library.

**Comment by robertodr** [comment]
I think we can officially tag version 2.0 and get a DOI. I'd suggest branching `release/v2.0` off of `master` and tag there, [as suggested here](http://www.bitsnbites.eu/a-stable-mainline-branching-model-for-git/)

**Comment by robertodr** [comment]
Closing this ticket. We have achieved these points now: we do have a release (albeit being an alpha) and a DOI. Work on deploying to Anaconda Cloud is (slowly) underway too conda-forge/staged-recipes#10347
