### ISSUE TITLE
Clean up compiler flags

### ISSUE THREAD

**Issue by robertodr** [dftlibs/xcfun#70]
I copy-pasted compiler flags without caring too much if they are still appropriate. They should be tested and cleaned up.

**Comment by robertodr** [comment]
I actually think they are only relevant for GNU. Mind filing a PR to remove them?

**Comment by robertodr** [comment]
@stigrj is this still relevant?

**Comment by stigrj** [comment]
You tell me #84

**Comment by robertodr** [comment]
:man_facepalming: Sorry for the noise... Closing.
