### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by ilfreddy** [dftlibs/xcfun#88]
## What the doc should contain (wishlist)
1. Examples on how to use XCFun in the different modes
2. A clear explanation of which order the densities and gradients should be provided as input
3. A clear explanation about the length of the input (density&gradient) and output (derivatives or potentials), and their ordering.
4. Some guidelines about how to write a functional for XCFun, ideally for different rungs in the ladder (LDA/GGA/metaGGA/....)

**Comment by robertodr** [comment]
I am doing a documentation pass in #106 (how to build, link, and autodoc-ing the API) #98 will bring _standalone_ examples in a Fortran and C which can be a good starting point to achieve the points in this issue.
