### ISSUE TITLE
Make it possible to set XC_MAX_ORDER within CMake

### ISSUE THREAD

**Issue by bast** [dftlibs/xcfun#97]
Currently `XC_MAX_ORDER` has to be set in `api/xcfun.h`. I need a higher `XC_MAX_ORDER` in LSDalton+OpenRSP+XCint.

I have "solved" this by creating a branch `radovan/openrsp`, deriving from `master` but a nicer way would be to set this during the configuration of the code. Sadly, I have to resist doing that right now due to too little time.

**Comment by robertodr** [comment]
See here: https://github.com/dftlibs/xcfun/blob/master/cmake/custom/xcfun.cmake#L19-L24
The variable is `XCFun_XC_MAX_ORDER`.

**Comment by bast** [comment]
Thanks! I will scrap that branch later today again.

**Comment by robertodr** [comment]
My fault, I did not properly document the variables...

**Comment by bast** [comment]
It seems that the variable name changed. I should have had a look in the XCint sources where this trick is used but with an outdated variable name :-)
